### ISSUE TITLE
Make `Map` off state more subtle to reduce motion

### ISSUE THREAD

**Issue by emmnull** [CPEUM/saint-constant#9]
instead of:
```css
figure {
  /* ... */
  opacity: 1;
  left: 100%;
  right: 0;
  top: 0;
  bottom: 0;
  /* ... */
}
```

try:
```css
figure {
  /* ... */
  opacity: 0;
  left: 50%;
  right: 0;
  top: 0;
  bottom: 0;
  /* ... */
}
```
